// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFmcDbM5LXIRP22MK1ts8ndqSlHqRQ4n4',
    appId: '1:917517970744:web:863d9cd61433ffe23ea5cd',
    messagingSenderId: '917517970744',
    projectId: 'pawg-52e10',
    authDomain: 'pawg-52e10.firebaseapp.com',
    databaseURL: 'https://pawg-52e10-default-rtdb.firebaseio.com',
    storageBucket: 'pawg-52e10.firebasestorage.app',
    measurementId: 'G-H00XSGRCKS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVqTnemLBb-y9b532LvSqnIwMuJzDnw4Y',
    appId: '1:917517970744:android:4d479cc9c12107ae3ea5cd',
    messagingSenderId: '917517970744',
    projectId: 'pawg-52e10',
    databaseURL: 'https://pawg-52e10-default-rtdb.firebaseio.com',
    storageBucket: 'pawg-52e10.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkqsPlJ3cqLn-qTbPHPbD8j3-FOL6rYiw',
    appId: '1:917517970744:ios:e4e40cfcd229695c3ea5cd',
    messagingSenderId: '917517970744',
    projectId: 'pawg-52e10',
    databaseURL: 'https://pawg-52e10-default-rtdb.firebaseio.com',
    storageBucket: 'pawg-52e10.firebasestorage.app',
    iosBundleId: 'com.example.firebasePetSocial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkqsPlJ3cqLn-qTbPHPbD8j3-FOL6rYiw',
    appId: '1:917517970744:ios:e4e40cfcd229695c3ea5cd',
    messagingSenderId: '917517970744',
    projectId: 'pawg-52e10',
    databaseURL: 'https://pawg-52e10-default-rtdb.firebaseio.com',
    storageBucket: 'pawg-52e10.firebasestorage.app',
    iosBundleId: 'com.example.firebasePetSocial',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFmcDbM5LXIRP22MK1ts8ndqSlHqRQ4n4',
    appId: '1:917517970744:web:139a2f88e281f04c3ea5cd',
    messagingSenderId: '917517970744',
    projectId: 'pawg-52e10',
    authDomain: 'pawg-52e10.firebaseapp.com',
    databaseURL: 'https://pawg-52e10-default-rtdb.firebaseio.com',
    storageBucket: 'pawg-52e10.firebasestorage.app',
    measurementId: 'G-57C8VCC4K3',
  );
}
